name: "setup"
description: "setup"
outputs: {}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: pnpm/action-setup@v4.0.0
      with:
        version: 7.9.3
        run_install: true
